### ISSUE TITLE
the site is not working

### ISSUE THREAD

**Issue by bakbuz** [ivanpaulovich/dotnet-new-caju#8]
https://caju.paulovich.net/ doesn't work

**Comment by ivanpaulovich** [comment]
Hi @bakbuz!

Since my azure account runs out of money the caju website stopped working, I am planning to reactivate it using Heroku soon.

In the meantime you can use the command line `dotnet new -i Paulovich.Caju`. I suggest you to check out the repo https://github.com/ivanpaulovich/clean-architecture-manga for the most updated docs and patterns.

Best!

**Comment by bakbuz** [comment]
> Hi @bakbuz!
> 
> Since my azure account runs out of money the caju website stopped working, I am planning to reactivate it using Heroku soon.
> 
> In the meantime you can use the command line `dotnet new -i Paulovich.Caju`. I suggest you to check out the repo https://github.com/ivanpaulovich/clean-architecture-manga for the most updated docs and patterns.
> 
> Best!

Thank you very much.
